/*
 * DO NOT EDIT!
 * 
 * Automatically generated source code by Pitch Developer Studio
 * Licensed to Guidarly Joseph, SEE, Project Edition
 *
 * Copyright (C) 2006-2023 Pitch Technologies AB. All rights reserved.
 * Use is subject to license terms.
 */

/**
 * Main package for the API generated by Pitch Developer Studio.
 * <p>
 * Start by creating an instance of the {@link core.HlaWorld} interface by calling
 * {@link core.HlaWorld.Factory#create HlaWorld.Factory.create()}.
 */
package core;
